//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonDTO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public System.Guid orderItemGuid { get; set; }
        public int OrderId { get; set; }
        public int serviceId { get; set; }
        public string serviceDate { get; set; }
        public string serviceName { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public string comments { get; set; }
        public string itemStatus { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
