//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonDTO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public int devoteeID { get; set; }
        public int MailAddressId { get; set; }
        public string orderDate { get; set; }
        public System.Guid orderGuid { get; set; }
        public short orderItemCount { get; set; }
        public string orderStatus { get; set; }
        public decimal orderTotal { get; set; }
        public string orderCreatedBy { get; set; }
        public string paymentStatus { get; set; }
        public string paymentMethodName { get; set; }
        public decimal refundedAmount { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
        public string checkNumber { get; set; }
        public string checkDepositDate { get; set; }
        public string checkRoutingNumber { get; set; }
        public string checkAccountNumber { get; set; }
        public string cardType { get; set; }
        public string cardName { get; set; }
        public string cardNumberMasked { get; set; }
        public string cardCVV2 { get; set; }
        public string cardExpirationMonth { get; set; }
        public string cardExpirationYear { get; set; }
        public string authorizationTransactionId { get; set; }
        public string authorizationTransactionCode { get; set; }
        public string comment1 { get; set; }
        public string comment2 { get; set; }
        public string comment3 { get; set; }
        public string refundTransactionId { get; set; }
        public string refundTransactionCode { get; set; }
        public string checkDepositRegisteredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
