//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonDTO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Requests_Transaction
    {
        public int Service_Req_Tran_ID { get; set; }
        public int Service_Request_ID { get; set; }
        public string TransactionID { get; set; }
        public string TransactionType { get; set; }
        public string Credit_Card_Type { get; set; }
        public string CardNumber { get; set; }
        public string CardExpiration { get; set; }
        public Nullable<double> RequestedAmount { get; set; }
        public Nullable<double> ApprovedAmount { get; set; }
        public string AuthCode { get; set; }
        public string AVSResponse { get; set; }
        public string CardCodeResponse { get; set; }
        public bool IsApproved { get; set; }
        public string TransactionMessage { get; set; }
        public string ResponseCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Service_Requests Service_Requests { get; set; }
    }
}
