//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonDTO.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service_Requests()
        {
            this.Service_Requests_Transaction = new HashSet<Service_Requests_Transaction>();
        }
    
        public int Service_Request_ID { get; set; }
        public Nullable<int> Devotee_ID { get; set; }
        public int Service_ID { get; set; }
        public System.DateTime Service_Date { get; set; }
        public Nullable<int> Priest_ID { get; set; }
        public Nullable<int> Payment_Type_ID { get; set; }
        public Nullable<int> Check_Number { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Devotee_ID_Original { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Service_Fee_Paid { get; set; }
        public Nullable<System.DateTime> Check_Deposit_Date { get; set; }
        public string Check_Deposit_Registered_By { get; set; }
        public string Comment1 { get; set; }
        public string Comment2 { get; set; }
        public string Comment3 { get; set; }
        public Nullable<System.DateTime> Check_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service_Requests_Transaction> Service_Requests_Transaction { get; set; }
    }
}
